name: epatriote_country_flag
description: Display country flag from your flutter app.
version: 0.0.2-dev
homepage:   https://epatriotecreative.github.io/epatriote_country_flag/
repository: https://github.com/ePatrioteCreative/epatriote_country_flag.git


environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # Register all country flag as an image asset
  assets:
    - assets/svg/
    - assets/png/